[general]
host = "0.0.0.0"
port = 80
root = "./"

log-level = "error"
log-remote-address = false

directory-listing = false
cache-control-headers = true

# Lejo vetëm domainin tënd për CORS
cors-allow-origins = "https://shpi.online"

index-files = "index.html"
ignore-hidden-files = true
disable-symlinks = true

[advanced]

[[advanced.headers]]
source = "**"
[advanced.headers.headers]
Cache-Control = "public, max-age=86400, immutable"
Pragma = "public"
Expires = "1d"
